### ISSUE TITLE
How's performance of this?

### ISSUE THREAD

**Issue by elbamos** [beniz/fiboheap#5]
I'm looking for a fibonacci implementation, and many of the ones floating around seem to have performance issues, do you have any timing results on this one? 

Thanks!

**Comment by beniz** [comment]
None, but it's easy to write a test. If you do so, please PR it!

**Comment by elbamos** [comment]
It's not so easy though because tests would have to be built for competing implementations. 

It's odd to me that such a well-known algorithm lacks an acknowledged-correct-and-efficient C++ implementation.

**Comment by beniz** [comment]
Lazyness is the developer's enemy. And there's a boost implementation, look it up!
